"""Render the five added tables from audited reviewer experiment summaries."""
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]


def table(name, caption, label, columns, headers, rows):
    folder = PAPER / "sections/revision_tables"
    folder.mkdir(parents=True, exist_ok=True)
    lines = ["% Generated by scripts/render_revision_tables.py.",
             r"\begin{table*}[!t]", r"\begin{revised}",
             r"\caption{\begin{revised}" + caption + r"\end{revised}}", r"\label{" + label + "}",
             r"\centering", r"\renewcommand{\arraystretch}{1.15}",
             r"\begin{tabularx}{\linewidth}{@{}" + columns + r"@{}}",
             r"\toprule", " & ".join(headers) + r"\\", r"\midrule"]
    lines += [" & ".join(map(str, row)) + r"\\" for row in rows]
    lines += [r"\bottomrule", r"\end{tabularx}", r"\end{revised}", r"\end{table*}"]
    (folder / f"{name}.tex").write_text("\n".join(lines) + "\n")


def main():
    data = json.loads((PAPER / "data/reviewer_experiments.json").read_text())
    test = data["groups"]["test"]
    rows = []
    conditions = [("Greedy, unguided", "unguided", None),
                  ("Greedy, guided", "guided", "seed13"),
                  ("Greedy, guided", "seed17", "seed17"),
                  ("Greedy, guided", "seed29", "seed29"),
                  ("Repair, unguided", "repair_unguided", None),
                  ("Repair, guided", "repair_guided", "seed13")]
    for title, key, model in conditions:
        s = test[key]
        assert s["legal"] == s["n"] == s["compared"] == 512
        rows.append([title, model[4:] if model else "n/a",
                     data["models"][model]["epoch"] if model else "n/a",
                     s["optimal"], f'{s["optimal_percent"]:.2f}', f'{s["mean_gap"]:.3f}'])
    table("seeds", "Original test set, additional training seeds, and optional repair. "
          "Every condition returns 512 legal candidates; all 512 exact references are available. "
          "Epoch denotes the validation-selected checkpoint.", "tab:revision-seeds", "Yrrrrr",
          ["Decoder", "Seed", "Epoch", r"\shortstack{Optimal\\count}",
           r"\shortstack{Optimal\\(\%)}", r"\shortstack{Mean\\gap}"], rows)

    rows = []
    for name in ["seed17", "seed29"]:
        full, removed = test[name], test[name+"_no_log"]
        rows.append([name[4:], data["models"][name]["epoch"],
                     data["models"][name+"_no_log"]["epoch"], full["optimal"],
                     removed["optimal"], f'{full["optimal_percent"]-removed["optimal_percent"]:+.2f}'])
    table("loss", "Matched log-loss ablation with default greedy decoding on 512 test rows. "
          "Full retains log supervision; no log sets only its coefficient to zero. "
          "All candidates pass replay. The difference is full minus no log in percentage points.",
          "tab:revision-loss", "Yrrrrr",
          ["Seed", r"\shortstack{Epoch\\full}", r"\shortstack{Epoch\\no log}",
           r"\shortstack{Optimal\\full}", r"\shortstack{Optimal\\no log}",
           r"\shortstack{Difference\\(points)}"], rows)

    rows = []
    for group, title in [("acyclic/custom", "Acyclic, original"), ("acyclic/pm4py", "Acyclic, PM4Py"),
                         ("loop/custom", "Loop, original"), ("loop/pm4py", "Loop, PM4Py")]:
        values = data["groups"][group]
        assert all(v["legal"] == v["compared"] == 128 for v in values.values())
        rows.append([title] + [f'{values[key]["optimal_percent"]:.1f}' for key in
                     ["unguided", "guided", "seed17", "seed29", "repair_unguided", "repair_guided"]])
    table("structures", r"Optimal candidate rates (\%) on structures excluded from training. "
          "Each row has 128 inputs from 64 trees and complete candidate/exact coverage. "
          "The three seeds use greedy decoding; guided repair uses seed 13.",
          "tab:revision-structures", "Yrrrrrr",
          ["Class, compiler", "Unguided", "Seed 13", "Seed 17", "Seed 29",
           r"\shortstack{Repair\\unguided}", r"\shortstack{Repair\\guided}"], rows)

    rows = []
    for log, title in [("roadtraffic", "Road traffic"), ("receipt", "Receipt"), ("sepsis", "Sepsis")]:
        for threshold in ["0.0", "0.5"]:
            values = data["groups"][f"real/{log}/{threshold}"]
            base = values["guided"]
            assert all(v["legal"] == v["compared"] == base["n"] for v in values.values())
            rows.append([title, threshold,
                         f'{base["optimal"]}/{base["n"]}',
                         f'{base["optimal_cases"]}/{base["cases"]}',
                         f'{values["repair_guided"]["optimal"]}/{base["n"]}',
                         f'{values["repair_unguided"]["optimal"]}/{base["n"]}'])
    table("real", "Held-out real-log cases. Fractions report optimal counts over all evaluated "
          "variants or cases. Greedy columns use seed 13. Repair columns are variant counts; "
          "guided repair also uses seed 13. All 652 variant/model inputs have exact references "
          "and legal candidates.", "tab:revision-real", "Yrrrrr",
          ["Log", "Threshold", r"\shortstack{Greedy\\variants}", r"\shortstack{Greedy\\cases}",
           r"\shortstack{Repair guided\\variants}", r"\shortstack{Repair unguided\\variants}"], rows)

    rows = []
    titles = [("unguided", "Greedy, unguided"), ("guided", "Greedy, guided"),
              ("repair_guided", "Repair, guided"), ("exact", "Exact A*"),
              ("discounted_a_star", "Discounted A*"), ("tandem_repeats", "Tandem repeats"),
              ("sliding_window", "Sliding window"), ("fixed_horizon", "Fixed horizon")]
    for name, title in titles:
        s = data["timing"][name]
        rows.append([title, f'{s["legal_calls"]}/{s["calls"]}',
                     f'{100*s["optimal_calls"]/s["calls"]:.2f}', f'{s["median_ms"]:.3f}',
                     f'[{s["iqr_ms"][0]:.3f}, {s["iqr_ms"][1]:.3f}]'])
    table("timing", "Common-boundary CPU timings, including final independent replay. "
          "Each method has 512 inputs and five calls per input. Time summaries aggregate "
          "the per-input medians. Optimality uses all attempted calls as denominator.",
          "tab:revision-timing", "Yrrrr",
          ["Method", "Legal calls", r"\shortstack{Optimal\\(\%)}",
           r"\shortstack{Median\\(ms)}", r"\shortstack{Interquartile range\\(ms)}"], rows)


if __name__ == "__main__":
    main()
